name: route_map_generator
description: Create route map quickly by annotation.
version: 0.0.18
homepage: https://github.com/emintolgahanpolat/route_map
repository: https://github.com/emintolgahanpolat/route_map
# publish_to: 'none'

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  analyzer: ">=7.2.0"
  build: ^2.4.2
  change_case: ^2.2.0
  flutter:
    sdk: flutter
  glob: ^2.1.3
  route_map: ^0.0.17
  source_gen: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


dependency_overrides:
  route_map:
    path: ../route_map/

