name: route_map_generator
description: Create route map quickly by annotation.
version: 0.0.17
repository: https://github.com/emintolgahanpolat/route_map
# publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  analyzer: ">=5.12.0"
  build: ^2.4.1
  change_case: ^2.1.0
  flutter:
    sdk: flutter
  glob: ^2.1.2
  route_map: ^0.0.17
  source_gen: ^1.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


dependency_overrides:
  route_map:
    path: ../route_map/

