name: route_map
description: Route Map is a convenient code generator for Navigator 2.0. Inspired by injectable.
version: 0.0.3
homepage: https://github.com/emintolgahanpolat/route_map

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: