name: route_map
description: Create route map quickly by annotation.
version: 0.0.1
homepage: https://github.com/emintolgahanpolat/route_map

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: